
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster} from "react-hot-toast";
import { LoadingProvider } from "./components/onboarding/LoadingContext";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script src="/config.js" strategy="beforeInteractive" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LoadingProvider>
          {children}
          {/* Toast notifications */}
          <Toaster position="top-right" />
        </LoadingProvider>
      </body>
    </html>
  );
}

